#!/bin/sh
case "$1 $2" in
  "account list") echo "Please run 'az login' to setup account." >&2; echo "[]"; exit 0 ;;
  "account get-access-token") echo "Please run 'az login' to setup account." >&2; exit 1 ;;
  *) exit 2 ;;
esac
